- hosts: webservers
  become: yes
  tasks:
    - name: copy built files to deploy-server
      copy:
        src: '/var/lib/jenkins/workspace/node_test/build/'
        dest: /home/ubuntu/
        

    - name: start node
      shell: 
        chdir: /home/ubuntu/
        cmd: /bin/bash startnode.sh
      become: yes

  
